Skip to content

## Navigation Menu

Toggle navigation

Sign in 

  * Product 

    * Actions

Automate any workflow 

    * Packages

Host and manage packages 

    * Security

Find and fix vulnerabilities 

    * Codespaces

Instant dev environments 

    * GitHub Copilot

Write better code with AI 

    * Code review

Manage code changes 

    * Issues

Plan and track work 

    * Discussions

Collaborate outside of code 

Explore
    * All features 
    * Documentation 
    * GitHub Skills 
    * Blog 

  * Solutions 

By size
    * Enterprise 
    * Teams 
    * Startups 

By industry
    * Healthcare 
    * Financial services 
    * Manufacturing 

By use case
    * CI/CD & Automation 
    * DevOps 
    * DevSecOps 

  * Resources 

Topics
    * AI 
    * DevOps 
    * Security 
    * Software Development 

Explore
    * Learning Pathways 
    * White papers, Ebooks, Webinars 
    * Customer Stories 
    * Partners 

  * Open Source 

    * GitHub Sponsors

Fund open source developers 

    * The ReadME Project

GitHub community articles 

Repositories
    * Topics 
    * Trending 
    * Collections 

  * Enterprise 

    * Enterprise platform

AI-powered developer platform 

Available add-ons
    * Advanced Security

Enterprise-grade security features 

    * GitHub Copilot

Enterprise-grade AI features 

    * Premium Support

Enterprise-grade 24/7 support 

  * Pricing



Search or jump to...

# Search code, repositories, users, issues, pull requests...

Search 

Clear




Search syntax tips 

#  Provide feedback 

We read every piece of feedback, and take your input very seriously.

Include my email address so I can be contacted

Cancel  Submit feedback 

#  Saved searches 

## Use saved searches to filter your results more quickly

Name

Query

To see all available qualifiers, see our documentation. 

Cancel  Create saved search 

Sign in 

Sign up  Reseting focus

You signed in with another tab or window. Reload to refresh your session. You signed out in another tab or window. Reload to refresh your session. You switched accounts on another tab or window. Reload to refresh your session. Dismiss alert

{{ message }}

rubin-dp0  / **tutorial-notebooks ** Public

  * Notifications  You must be signed in to change notification settings
  * Fork 16
  * Star  31




  * Code
  * Issues 0
  * Pull requests 2
  * Actions
  * Projects 0
  * Security
  * Insights



Additional navigation options

  * Code 
  * Issues 
  * Pull requests 
  * Actions 
  * Projects 
  * Security 
  * Insights 



## Commit

Permalink

This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

Update DP03_01_Introduction_to_DP03.ipynb 

Browse files Browse the repository at this point in the history
    
    
    Added review edits/changes

  * Loading branch information



ryanlauastro committed Jul 28, 2023

1 parent 0ef6550 commit f5bee88

Showing **1 changed file** with **12 additions** and **10 deletions**. 

  * Whitespace
  * Ignore whitespace



  * Split
  * Unified



##  There are no files selected for viewing 

22 changes: 12 additions & 10 deletions  22  DP03_01_Introduction_to_DP03.ipynb

Show comments 

View file  Edit file  Delete file 

This file contains bidirectional Unicode text that may be interpreted or compiled differently than what appears below. To review, open the file in an editor that reveals hidden Unicode characters. Learn more about bidirectional Unicode characters

Show hidden characters 

Original file line number Diff line number Diff line change  
Expand Up @@ -51,7 +51,7 @@  
"id": "8740f32b-3d92-4c10-8d88-46e600a63a96",  
"metadata": {},  
"source": [  
"**Credit:** The DP0.3 data set was generated by members of the Rubin Solar System Pipelines and Commissioning teams, with help from the LSST Solar System Science Collaboration, in particular: Pedro Bernardinelli, Jake Kurlander, Joachim Moeyens, Samuel Cornwall, Ari Heinze, Steph Merritt, Lynne Jones, Siegfried Eggl, Meg Schwamb, and Mario Juric.\n",  
"**Credit:** The DP0.3 data set was generated by members of the Rubin Solar System Pipelines and Commissioning teams, with help from the LSST Solar System Science Collaboration, in particular: Pedro Bernardinelli, Jake Kurlander, Joachim Moeyens, Samuel Cornwall, Ari Heinze, Steph Merritt, Lynne Jones, Siegfried Eggl, Meg Schwamb, and Mario Jurić.\n",  
"\n",  
"Mario Jurić provided essential assistance in the initial stages of creating this notebook. The notebook authors would also like to acknowledge help from Leanne Guy, Pedro Bernardinelli, Sarah Greenstreet, Megan Schwamb, Brian Rogers, Niall McElroy, and Jake Vanderplass, among others."  
]  
Expand All @@ -77,7 +77,7 @@  
"For the DP0.3 simulation, only moving objects were simulated, and only catalogs were created (there are no images).\n",  
"The DP0.3 simulation is *entirely independent of and separate from* the DP0.2 simulation.\n",  
"\n",  
"DP0.3 is a hybrid catalog that contains both real and simulated Solar System objects (asteroids, near-earth objects, Trojans, trans-Neptunian objects, and even a simulated spaceship... but no comets, major planets, or the Moon).\n",  
"DP0.3 is a hybrid catalog that contains both real and simulated Solar System objects (asteroids, near-earth objects, Trojans, trans-Neptunian objects, comets, and even a simulated spaceship... but no major planets nor the Moon).\n",  
"See the <a href=\"https://dp0-3.lsst.io\">DP0.3 documentation</a> for more information about how the hybrid catalog was created.\n",  
"\n",  
"In Rubin Operations, these tables would be constantly changing, updated every day with the results of\n",  
Expand Down Expand Up @@ -213,7 +213,7 @@  
"\n",  
"During Rubin Operations, Solar System Processing will occur in the daytime, after a night of observing.\n",  
"It will link together the difference-image detections of moving objects and report discoveries\n",  
"to the <a href=\"https://minorplanetcenter.net/https://minorplanetcenter.net/\">Minor Planet Center</a> (MPC),\n",  
"to the <a href=\"https://minorplanetcenter.net\">Minor Planet Center</a> (MPC),\n",  
"as well as compute derived properties (magnitudes, phase-curve fits, coordinates in various systems).\n",  
"\n",  
"The MPC will calculate the orbital parameters and these results will be passed back to Rubin, and stored\n",  
Expand Down Expand Up @@ -349,7 +349,7 @@  
"source": [  
"Define a search range for `ssObjectId` that would return no more than 1% of all objects in `MPCORB`. We will do this by estimating a new minimum `ssObjectId` that is 1% _below_ the maximum `ssObjectId` for the full range of `ssObjectId` values.\n",  
"\n",  
"> **Notice:** Since the _range_ of `ssObjectId`'s (-9223370383071521539 --> +92233708751260691079223370875126069107) is much larger than the number of _rows_ in the `MPCORB` table (14600302), we don't expect to get _exactly_ 1% of the rows from `MPCORB` via this method, but we should get approximately 1%, as long as the `ssObjectId` values are distributed reasonably uniformly over their large range.\n"  
"> **Notice:** Since the _range_ of `ssObjectId`'s (-9223370383071521539 --> +9223370875126069107) is much larger than the number of _rows_ in the `MPCORB` table (14600302), we don't expect to get _exactly_ 1% of the rows from `MPCORB` via this method, but we should get approximately 1%, as long as the `ssObjectId` values are distributed reasonably uniformly over their large range.\n"  
]  
},  
{  
Expand Down Expand Up @@ -495,7 +495,7 @@  
"source": [  
"### 3.4. Plot histograms of orbital elements\n",  
"\n",  
"Wikipedia provides a decent <a href=\"https://en.wikipedia.org/wiki/Orbital_elementshttps://en.wikipedia.org/wiki/Orbital_elements\">beginner-level guide to orbital elements</a>.\n",  
"Wikipedia provides a decent <a href=\"https://en.wikipedia.org/wiki/Orbital_elements\">beginner-level guide to orbital elements</a>.\n",  
"\n",  
"For a quick reference, distributions are shown below for six key orbital elements."  
]  
Expand All @@ -509,7 +509,7 @@  
},  
"outputs": [],  
"source": [  
"fig, ax = plt.subplots(2, 3, figsize=(8, 4), sharey=True)\n",  
"fig, ax = plt.subplots(2, 3, figsize=(10, 6), sharey=False)\n",  
"ax[0, 0].hist(df['e'], bins=100, log=True)\n",  
"ax[0, 0].set_xlabel('Eccentricity')\n",  
"ax[0, 0].set_ylabel('log(Number)')\n",  
Expand All @@ -519,12 +519,14 @@  
"ax[0, 2].hist(df['mpcH'], bins=100, log=True)\n",  
"ax[0, 2].set_xlabel('Absolute Magnitude, H (mag)')\n",  
"ax[0, 2].set_ylabel('log(Number)')\n",  
"ax[1, 0].hist(df['node'], bins=50, log=True)\n",  
"ax[1, 0].hist(df['node'], bins=50)\n",  
"ax[1, 0].set_xlabel('Longitude of Ascending Node (deg)')\n",  
"ax[1, 0].set_ylabel('log(Number)')\n",  
"ax[1, 1].hist(df['peri'], bins=50, log=True)\n",  
"ax[1, 0].set_ylabel('Number')\n",  
"ax[1, 0].set_ylim(0,3500)\n",  
"ax[1, 1].hist(df['peri'], bins=50)\n",  
"ax[1, 1].set_xlabel('Argument of Perihelion (deg)')\n",  
"ax[1, 1].set_ylabel('log(Number)')\n",  
"ax[1, 1].set_ylabel('Number')\n",  
"ax[1, 1].set_ylim(0,3500)\n",  
"ax[1, 2].hist(df['q'], bins=100, log=True)\n",  
"ax[1, 2].set_xlabel('Perihelion Distance (AU)')\n",  
"ax[1, 2].set_ylabel('log(Number)')\n",  
Expand Down  
  
Toggle all file notes Toggle all file annotations

###  0 comments on commit `f5bee88`

Please sign in to comment. 

## Footer

© 2024 GitHub, Inc. 

### Footer navigation

  * Terms
  * Privacy
  * Security
  * Status
  * Docs
  * Contact
  * Manage cookies 
  * Do not share my personal information 



You can’t perform that action at this time. 
